STOR-1433: Restart `azure-disk-csi-driver-controller` Pods if metrics-serving-cert changed
openshift/azure-disk-csi-driver-operator pull request #91
Opened 2023-08-04 08:44 UTC by Phaow

## STOR-1433: Restart `azure-disk-csi-driver-controller` Pods if metrics-serving-cert changed
- Adding WithSecretHashAnnotationHook() for azure-disk-csi-driver-controller ensures that new annotation is published in azure-disk-csi-driver-controller deployment. This, in turn, leads to controller pods restart.

2023-08-04 15:36 UTC, mpatlasov commented
/assign @mpatlasov

2023-08-07 00:28 UTC, Phaow commented
/test e2e-azure

2023-08-07 00:32 UTC, mpatlasov requested changes

2023-08-07 00:32 UTC, mpatlasov commented on pkg/operator/starter.go
> +		csidrivernodeservicecontroller.WithSecretHashAnnotationHook(defaultNamespace, metricsCertSecretName, secretInformer),
This line is redundant: it would lead to restarting csi drivers, but they do not depend on `azure-disk-csi-driver-controller-metrics-serving-cert`.

2023-08-07 00:34 UTC, mpatlasov commented
@Phaow , please remove that redundant line in `.WithCSIDriverNodeService(...)`. Other than that, the PR looks fine.

2023-08-07 00:47 UTC, Phaow commented on pkg/operator/starter.go
> +		csidrivernodeservicecontroller.WithSecretHashAnnotationHook(defaultNamespace, metricsCertSecretName, secretInformer),
Got it. Thanks for clarifying! Addressed.

2023-08-07 00:47 UTC, Phaow commented
> @Phaow , please remove that redundant line in `.WithCSIDriverNodeService(...)`. Other than that, the PR looks fine.

Sure, updated, thank you!

2023-08-07 00:47 UTC, Phaow commented
/label tide/merge-method-squash

2023-08-07 01:28 UTC, mpatlasov approved these changes

2023-08-07 01:30 UTC, mpatlasov commented
/label docs-approved
/label px-approved
/lgtm
/approved

2023-08-07 03:36 UTC, Phaow commented
/retest-required

2023-08-07 08:34 UTC, Phaow commented
Pre verifiy passed with the pre merged build `4.14.0-0.ci.test-2023-08-07-014130-ci-ln-mnc9yfk-latest`

```console
# After the metrics-serving-cert secret changed, driver controller restarted
$ oc delete secret/azure-disk-csi-driver-controller-metrics-serving-cert
secret "azure-disk-csi-driver-controller-metrics-serving-cert" deleted

$ oc get po
NAME                                                READY   STATUS            RESTARTS   AGE
azure-disk-csi-driver-controller-765c59bd87-brntd   11/11   Running           0          10s
azure-disk-csi-driver-controller-765c59bd87-lbvcx   0/11    PodInitializing   0          4s
azure-disk-csi-driver-node-47ckd                    3/3     Running           0          5h20m
azure-disk-csi-driver-node-hztpn                    3/3     Running           0          5h20m
azure-disk-csi-driver-node-jf22m                    3/3     Running           0          5h20m
azure-disk-csi-driver-node-jxjkk                    3/3     Running           0          5h7m
azure-disk-csi-driver-node-n26ws                    3/3     Running           0          5h7m
azure-disk-csi-driver-node-t7sgw                    3/3     Running           0          5h7m
azure-disk-csi-driver-operator-648d5bbc45-7gllj     1/1     Running           0          5h20m
azure-file-csi-driver-controller-8558659fd6-gxtsc   9/9     Running           0          5h19m
azure-file-csi-driver-controller-8558659fd6-mb9gv   9/9     Running           0          5h20m
azure-file-csi-driver-node-2b84z                    3/3     Running           0          5h7m
azure-file-csi-driver-node-6qgd7                    3/3     Running           0          5h20m
azure-file-csi-driver-node-pdp76                    3/3     Running           0          5h7m
azure-file-csi-driver-node-rgtxt                    3/3     Running           0          5h7m
azure-file-csi-driver-node-thprg                    3/3     Running           0          5h20m
azure-file-csi-driver-node-zt84z                    3/3     Running           0          5h20m
azure-file-csi-driver-operator-5648bb47cd-n9xth     1/1     Running           0          5h20m

$ oc get po -l app=azure-disk-csi-driver-controller
NAME                                                READY   STATUS    RESTARTS   AGE
azure-disk-csi-driver-controller-765c59bd87-brntd   11/11   Running   0          7m31s
azure-disk-csi-driver-controller-765c59bd87-lbvcx   11/11   Running   0          7m25s

```

2023-08-07 08:35 UTC, Phaow commented
/label qe-approved

2023-08-07 08:39 UTC, merged